### ISSUE TITLE
50K Battery Box cannot be crafted without STB recipe book.

### ISSUE THREAD

**Issue by TeamOah** [Slimefun/SensibleToolbox#78] opened 2021-05-16 21:04 UTC
## :round_pushpin: Description (REQUIRED)

The 50k battery box cannot be crafted normally without the assistance of the stb recipe book, which is disabled on some servers.

## :bookmark_tabs: Steps to reproduce the Issue (REQUIRED)

The 50k box does not show up in the craft output slot.

## :bulb: Expected behavior (REQUIRED)

The box should be craftable with a craft table.
It CAN be crafted using this 'workaround method described in the video, however, on some servers (like the one I play) the recipe book is not craftable.

https://user-images.githubusercontent.com/80911807/118412506-1035a980-b660-11eb-95f7-9145994bd1bc.mp4

## :compass: Environment (REQUIRED)

This has never worked since I was introduced to STB last year.

**Comment by TheBusyBiscuit** [comment] 2021-05-16 21:11
Duplicate of #47 and missing versions.

**Closed by TheBusyBiscuit** 2021-05-16 21:11 UTC
Labels: invalid
